name: Go

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   golangci:
      runs-on: ubuntu-18.04
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-go@v2
           with:
              stable: 'false'
              go-version: '1.17'

         - name: Lint
           run: |
              curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
              golangci-lint run
   build:
      name: Test
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Set up Go 1.x
           uses: actions/setup-go@v2
           with:
              go-version: ^1.17
           id: go
         - name: Test
           run: go test -v -race ./...
